{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "plugin",
    "version": "1.0.0927",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.0927.jar",
          "url": "plugin-1.0.0927.jar",
          "size": 213347,
          "sha512": "e0aebb222d26cc7f1680bb832092564c62e02909479ac2b9776da9fb91cf0c8ff1ef2692b61afb48783f04e7a5e7063333a0daf1abe6859684107e840633f93a",
          "sha256": "3fd38644e0dd067824f4c38b6e89316962ef6f7756183c024daf5d9bcb2cac23",
          "sha1": "e8d407a06cd2091c5424b6f0f5050f669e05424d",
          "md5": "0361ad48ce9a9ab0afe2e8a30c8ab5c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0927.jar",
          "url": "plugin-1.0.0927.jar",
          "size": 213347,
          "sha512": "e0aebb222d26cc7f1680bb832092564c62e02909479ac2b9776da9fb91cf0c8ff1ef2692b61afb48783f04e7a5e7063333a0daf1abe6859684107e840633f93a",
          "sha256": "3fd38644e0dd067824f4c38b6e89316962ef6f7756183c024daf5d9bcb2cac23",
          "sha1": "e8d407a06cd2091c5424b6f0f5050f669e05424d",
          "md5": "0361ad48ce9a9ab0afe2e8a30c8ab5c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-1.0.0927-sources.jar",
          "url": "plugin-1.0.0927-sources.jar",
          "size": 150900,
          "sha512": "ab603024473a33f649eb1765beae718520ac63f4c252c3f830405ffa4df892729859f015630d8aeeff162ffa296423b8a8637b8bff6c7be69982f7fd641a509d",
          "sha256": "37a4bf499594f56e6ff75fdf374fffda62ae42bb29c04b2a3bfcb37af8e5a1c9",
          "sha1": "905fe713c971ca0334479cae1323bd772d90515b",
          "md5": "73f031a443c8bf9721a231c7c93ed6fc"
        }
      ]
    }
  ]
}
