{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "jar-optimizer",
    "version": "1.0.1102",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-optimizer-1.0.1102.jar",
          "url": "jar-optimizer-1.0.1102.jar",
          "size": 29340,
          "sha512": "b270d9f6b42a44b717a4b521e416d526778c2423fbd4ea49b4fda9ad35833bdae662684eed4bc414c11349c9fd9ac12d85806a8947afed71dc6823021b2e6806",
          "sha256": "7ffead64d6197328fb8fe42c2eab8212dab99dcca711c56da20e2c1ea91899f3",
          "sha1": "b34997fd0eaf01c12efb74d6b1bf8059cba9755f",
          "md5": "167f5db2318be5707af2bf6eff130632"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "jar-optimizer-1.0.1102.jar",
          "url": "jar-optimizer-1.0.1102.jar",
          "size": 29340,
          "sha512": "b270d9f6b42a44b717a4b521e416d526778c2423fbd4ea49b4fda9ad35833bdae662684eed4bc414c11349c9fd9ac12d85806a8947afed71dc6823021b2e6806",
          "sha256": "7ffead64d6197328fb8fe42c2eab8212dab99dcca711c56da20e2c1ea91899f3",
          "sha1": "b34997fd0eaf01c12efb74d6b1bf8059cba9755f",
          "md5": "167f5db2318be5707af2bf6eff130632"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-optimizer-1.0.1102-sources.jar",
          "url": "jar-optimizer-1.0.1102-sources.jar",
          "size": 4516,
          "sha512": "65a5b06c104477e36978bd061ef861e6037fd5067a27cc9330936c42c8a25a8b4affedfeef40475bece6c7a381c4ad23d6180fc71373b4aaee1470febf4893c2",
          "sha256": "167a07c23913cc6427e12083133609c22136c2ed1ff8ca51aceb27720da299bf",
          "sha1": "b702436ec448acdb498643340b819ec6e3ec65ba",
          "md5": "b446a209776e8548ac05519260671a8d"
        }
      ]
    }
  ]
}
