{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "plugin",
    "version": "1.0.1006",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.1006.jar",
          "url": "plugin-1.0.1006.jar",
          "size": 210821,
          "sha512": "418fb81ab5f3dc5facc54f1e3380f497512ed48b7e1be1a148c35298a28004f6399e6fe3b16355b6dd0f208c23f499ef6ef4c502e867d40ee424106aad388f7e",
          "sha256": "68c6480e266f4508605ca680740d9086a0170a9991b2e45e382c101501826c53",
          "sha1": "402bf1b466a41f2a51284e2153f5030259f646f5",
          "md5": "538b56cd71b70e58c4b9e8296269368d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.1006.jar",
          "url": "plugin-1.0.1006.jar",
          "size": 210821,
          "sha512": "418fb81ab5f3dc5facc54f1e3380f497512ed48b7e1be1a148c35298a28004f6399e6fe3b16355b6dd0f208c23f499ef6ef4c502e867d40ee424106aad388f7e",
          "sha256": "68c6480e266f4508605ca680740d9086a0170a9991b2e45e382c101501826c53",
          "sha1": "402bf1b466a41f2a51284e2153f5030259f646f5",
          "md5": "538b56cd71b70e58c4b9e8296269368d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-1.0.1006-sources.jar",
          "url": "plugin-1.0.1006-sources.jar",
          "size": 150430,
          "sha512": "c0d10d52e95e65cf4100e09ab350b9336f649b18b1e21d0d7a8c55447037af959f7f07c4d868d275730ad295ddcf93bc498283999e24f0264bfe3a31169bcfa8",
          "sha256": "39d3d9886b95c6713af83b6b3da3c7f11463f741e71388be5c1427e394a29e10",
          "sha1": "b66baa890e7b45541d9ab108decc8a5a0a64caf7",
          "md5": "253bb35345d3eb0fd36a58b280d4756a"
        }
      ]
    }
  ]
}
