{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "plugin",
    "version": "1.0.0804",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.0804.jar",
          "url": "plugin-1.0.0804.jar",
          "size": 213347,
          "sha512": "0c9b25bc11c82da61e6cc85c236ec68677b5028fad483969da375c09aaee32ea76c16db477664dc5afb149569630211e4f7b4f993d6319fc491666cbf03c431f",
          "sha256": "c3afcd3e97f1ef08b099ff8319dd4bff738ce657bb2d5c1452092c1645e3bfe8",
          "sha1": "53fbd1883eb0919b07bf7b58682b9393c07b0beb",
          "md5": "ea8966c9410e98232dec1c897b41f7bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0-RC"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.0804.jar",
          "url": "plugin-1.0.0804.jar",
          "size": 213347,
          "sha512": "0c9b25bc11c82da61e6cc85c236ec68677b5028fad483969da375c09aaee32ea76c16db477664dc5afb149569630211e4f7b4f993d6319fc491666cbf03c431f",
          "sha256": "c3afcd3e97f1ef08b099ff8319dd4bff738ce657bb2d5c1452092c1645e3bfe8",
          "sha1": "53fbd1883eb0919b07bf7b58682b9393c07b0beb",
          "md5": "ea8966c9410e98232dec1c897b41f7bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-1.0.0804-sources.jar",
          "url": "plugin-1.0.0804-sources.jar",
          "size": 149803,
          "sha512": "ec5ef5f703c4d136166c1c0b1df81892f7e92bdb503643fc1ed4df841d43ce06cbd01d6091202859b3a0c6a50706da3343f231b59330ba79935b181b05f0e35d",
          "sha256": "d167989203ecd7084e2513c76d6934d6ee61070cbad565c0998537492c908a65",
          "sha1": "53ac0d41ff99b1bef4b16430ac467cdd7dd02a62",
          "md5": "ec1a54f84574958f514ec7b6a279cf12"
        }
      ]
    }
  ]
}
