{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "mod-loader-runtime",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "mod-loader-runtime-1.0.jar",
          "url": "mod-loader-runtime-1.0.jar",
          "size": 9828,
          "sha512": "6189eff95be41508106379ed73b14b56dec57fb23d10dcc9213d6146ed6e839ddd09ef0eec98fafb733f4f59c81c3855a63622e7daa4efce92913d2259e6a10d",
          "sha256": "7ac40216268539fe2031907e0b74f89a32bbc13ded0a2553e8af9dcad33366f8",
          "sha1": "e0a77b51f0653dcd1c9ebd66eca7f61eed06c4c8",
          "md5": "f103643a97ce17c3155dcd4d1bad5d65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        }
      ],
      "files": [
        {
          "name": "mod-loader-runtime-1.0.jar",
          "url": "mod-loader-runtime-1.0.jar",
          "size": 9828,
          "sha512": "6189eff95be41508106379ed73b14b56dec57fb23d10dcc9213d6146ed6e839ddd09ef0eec98fafb733f4f59c81c3855a63622e7daa4efce92913d2259e6a10d",
          "sha256": "7ac40216268539fe2031907e0b74f89a32bbc13ded0a2553e8af9dcad33366f8",
          "sha1": "e0a77b51f0653dcd1c9ebd66eca7f61eed06c4c8",
          "md5": "f103643a97ce17c3155dcd4d1bad5d65"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-loader-runtime-1.0-all.jar",
          "url": "mod-loader-runtime-1.0-all.jar",
          "size": 126657,
          "sha512": "eac1b9668320aaf3ae1c0014a744a23507ae51b31e763da97bad8cdcb969af78b264f1e87480e11a9216274060dc45a35c9bf7ee13b20bf8d29cc291e1621f21",
          "sha256": "98b0c950103da0f41c46e33121041a17d7953f293405272081bad41a238ec621",
          "sha1": "fd819691d49ad9e9a41ceed8bba4aeb13c2b5c02",
          "md5": "311a3b4a0c70a79ea9f87c9b2c812634"
        }
      ]
    }
  ]
}
