{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "mod-loader-plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.0.jar",
          "url": "mod-loader-plugin-1.0.jar",
          "size": 240285,
          "sha512": "d291642d9a50fec6c6fd0fd387ad3a0502cc2826f0e037f868deed376b9c47f094f0800ec069cb96eead57f164e898bf8418c4970cd90d4338be17d3c9251a45",
          "sha256": "dece5014783b8d7805ace51d28013ffec40ca749c22d0130f62e8fc9ac1225d3",
          "sha1": "46687241c402ff41c250070e520a1c8de851dfc0",
          "md5": "9b85e888168ca6a3183633441703b0bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "mod-loader-plugin-1.0.jar",
          "url": "mod-loader-plugin-1.0.jar",
          "size": 240285,
          "sha512": "d291642d9a50fec6c6fd0fd387ad3a0502cc2826f0e037f868deed376b9c47f094f0800ec069cb96eead57f164e898bf8418c4970cd90d4338be17d3c9251a45",
          "sha256": "dece5014783b8d7805ace51d28013ffec40ca749c22d0130f62e8fc9ac1225d3",
          "sha1": "46687241c402ff41c250070e520a1c8de851dfc0",
          "md5": "9b85e888168ca6a3183633441703b0bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.0-sources.jar",
          "url": "mod-loader-plugin-1.0-sources.jar",
          "size": 150883,
          "sha512": "c35d298c86fa069fe981411d6342427bd71ef7888dda1575b8805578d7dfa0028f8af6ce90eb5ebc01902cfd227197b0ab7c169733456e7a095cd8dde41b51e3",
          "sha256": "98c0316033e1c3389578261a2535f98715dce6d4d4085b3be44fce5f699ebeb3",
          "sha1": "96101e1060d2e3d222b3522e630b9dfe56635e2f",
          "md5": "1bf61a891fbef437b3f3a42c47091b22"
        }
      ]
    }
  ]
}
