{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "fast-remapper",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fast-remapper-1.0.jar",
          "url": "fast-remapper-1.0.jar",
          "size": 369000,
          "sha512": "6d3f89007ecb446c34d7f4bfa7ab754da1baa47640de4cb7b3929857a563c1cec909f0da3d800e12310fdfdfb7b088114ed4723c972b88f1625703b5e8ae4371",
          "sha256": "f4cad6c844a42b6b98c8c92c2e8e389b381395dc3e2bac1f4a1408b7a3b21a62",
          "sha1": "e63a04727244012d4f8f54bb355ca99c2f593a18",
          "md5": "d25786db33ec7ee93afaf9dfbec6fd8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "fast-remapper-1.0.jar",
          "url": "fast-remapper-1.0.jar",
          "size": 369000,
          "sha512": "6d3f89007ecb446c34d7f4bfa7ab754da1baa47640de4cb7b3929857a563c1cec909f0da3d800e12310fdfdfb7b088114ed4723c972b88f1625703b5e8ae4371",
          "sha256": "f4cad6c844a42b6b98c8c92c2e8e389b381395dc3e2bac1f4a1408b7a3b21a62",
          "sha1": "e63a04727244012d4f8f54bb355ca99c2f593a18",
          "md5": "d25786db33ec7ee93afaf9dfbec6fd8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fast-remapper-1.0-sources.jar",
          "url": "fast-remapper-1.0-sources.jar",
          "size": 32814,
          "sha512": "80bfe397e17f4196f90052458b773e5e39c0281ddb5a6c71b7808f785ba409c9a168db8c17fe2bb70746fce88b689ffb0f76452f46d38b2f2f5fdd38e5a2c183",
          "sha256": "be2b881b0b76256e0bb2a5a96088a10438b14ff0429e5c5c880cbb59939fc159",
          "sha1": "9b3728e39ddb88d75aac196e0d36ada40678a508",
          "md5": "ddce45b7405ff665fb24537ba0f19f25"
        }
      ]
    }
  ]
}
