{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "jar-optimizer",
    "version": "1.0.1113",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "jar-optimizer-1.0.1113.jar",
          "url": "jar-optimizer-1.0.1113.jar",
          "size": 29340,
          "sha512": "94557a69ca375c145f333b3bd76beaa5b8728ae8bb9cde09df6703b6026afa576603270bcfa88aa5c31e4717bb17b2a1ae321ef462a06da74ace63c96b359ee3",
          "sha256": "1ca2d9975f90c51b6297cc0a55d779a82313953bea84045483a23284bf6ef4f3",
          "sha1": "882f6012da7a1654a321a248844ce9b98756f023",
          "md5": "2fe47b619700d8bbfd641a488ed6ec91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.13"
          }
        },
        {
          "group": "org.apache.bcel",
          "module": "bcel",
          "version": {
            "requires": "6.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "jar-optimizer-1.0.1113.jar",
          "url": "jar-optimizer-1.0.1113.jar",
          "size": 29340,
          "sha512": "94557a69ca375c145f333b3bd76beaa5b8728ae8bb9cde09df6703b6026afa576603270bcfa88aa5c31e4717bb17b2a1ae321ef462a06da74ace63c96b359ee3",
          "sha256": "1ca2d9975f90c51b6297cc0a55d779a82313953bea84045483a23284bf6ef4f3",
          "sha1": "882f6012da7a1654a321a248844ce9b98756f023",
          "md5": "2fe47b619700d8bbfd641a488ed6ec91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jar-optimizer-1.0.1113-sources.jar",
          "url": "jar-optimizer-1.0.1113-sources.jar",
          "size": 4516,
          "sha512": "3fb2f9eaeb1b12e6234e1317627111b07321bed0c3d0106cb2277f8a29dd652f752381e8ecf101c83bda3511a5b44d77c93f3772924a317df8e1db95aca9cdcc",
          "sha256": "8dd915c9e5f7ad93b43ed8b4b98752ac99868ea09b15f5993a1dad8ab656455e",
          "sha1": "f555acdbb3dec766b645d44b9d728151453ac663",
          "md5": "b285fce16590ceed77ed11da1c929a2e"
        }
      ]
    }
  ]
}
