{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "plugin",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 220580,
          "sha512": "41a391f4c7d971ae138f4f9d9ba759616f2846be0b1d6e0ae6996c57f3c8e7696e161f2f1a2b44f0a9962fc04e4f13fcc65c1ff4eba274c764ef9714ca3c3a5e",
          "sha256": "a053a2af09ec3bf694a9a650ef8b6d2756e5dc5620835d72edeedc91f71e050b",
          "sha1": "f987a7ecd319387dc540086307549e8f36db88b0",
          "md5": "4835e73e490ea369e7900c5c07d906eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.jar",
          "url": "plugin-1.0.jar",
          "size": 220580,
          "sha512": "41a391f4c7d971ae138f4f9d9ba759616f2846be0b1d6e0ae6996c57f3c8e7696e161f2f1a2b44f0a9962fc04e4f13fcc65c1ff4eba274c764ef9714ca3c3a5e",
          "sha256": "a053a2af09ec3bf694a9a650ef8b6d2756e5dc5620835d72edeedc91f71e050b",
          "sha1": "f987a7ecd319387dc540086307549e8f36db88b0",
          "md5": "4835e73e490ea369e7900c5c07d906eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-1.0-sources.jar",
          "url": "plugin-1.0-sources.jar",
          "size": 150883,
          "sha512": "c35d298c86fa069fe981411d6342427bd71ef7888dda1575b8805578d7dfa0028f8af6ce90eb5ebc01902cfd227197b0ab7c169733456e7a095cd8dde41b51e3",
          "sha256": "98c0316033e1c3389578261a2535f98715dce6d4d4085b3be44fce5f699ebeb3",
          "sha1": "96101e1060d2e3d222b3522e630b9dfe56635e2f",
          "md5": "1bf61a891fbef437b3f3a42c47091b22"
        }
      ]
    }
  ]
}
