{
  "formatVersion": "1.1",
  "component": {
    "group": "net.darkmeow",
    "module": "mod-loader-plugin",
    "version": "1.0.1221",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.0.1221.jar",
          "url": "mod-loader-plugin-1.0.1221.jar",
          "size": 206807,
          "sha512": "98b045e40d36ebedfe9664b1d3072bcde6bfbac36eb1a139c31ae46c3f7f68a836bbc19017dd4dbe158c247e03e3103d9a8e59f80c42ec32969594d417599692",
          "sha256": "d4b15b837e03eeaaf5782c9f1cde136402f0123591d63974a96ae7043177a646",
          "sha1": "8f95b20b2210908a2f67dbe2a190ce41275e97f0",
          "md5": "c01063253ddd22622453aa40830eb3a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mod-loader-plugin-1.0.1221.jar",
          "url": "mod-loader-plugin-1.0.1221.jar",
          "size": 206807,
          "sha512": "98b045e40d36ebedfe9664b1d3072bcde6bfbac36eb1a139c31ae46c3f7f68a836bbc19017dd4dbe158c247e03e3103d9a8e59f80c42ec32969594d417599692",
          "sha256": "d4b15b837e03eeaaf5782c9f1cde136402f0123591d63974a96ae7043177a646",
          "sha1": "8f95b20b2210908a2f67dbe2a190ce41275e97f0",
          "md5": "c01063253ddd22622453aa40830eb3a4"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.0.1221-all.jar",
          "url": "mod-loader-plugin-1.0.1221-all.jar",
          "size": 96273809,
          "sha512": "09639d636fc2211fe25571d5c6aa4b5d290b7407aa6b720d4e174bb3c406744599c445652b0967910af3f880b90e5ea6e09e8ea5f2e2164f9e94228b81ba0ce7",
          "sha256": "af0c68c3614e8e3e860db621e0a733da7ec78259bab9efa0286560293809ee50",
          "sha1": "994374fdc40af2e80109eb0c0622951f64e5dfd5",
          "md5": "373fd785edfa0d631ad9f0b3e2336894"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mod-loader-plugin-1.0.1221-sources.jar",
          "url": "mod-loader-plugin-1.0.1221-sources.jar",
          "size": 149653,
          "sha512": "13fd42310a7b71f7e36955e832dcffcface2dee20bfd836a1d5a090d5499a1582fbf28a3cdf0192259a14895301797b8b3c308ce47cdc70cdf701bf2067024d8",
          "sha256": "c0f1a263685753014c03a910a99983449368c479c6d15c862a4bbd5995e41ce0",
          "sha1": "ccdda6b1343308445e75b8da694b393fdac58375",
          "md5": "3015ff7df495d25a94449a62b4f1d243"
        }
      ]
    }
  ]
}
